server:
  port: 8080

spring:
  application:
    name: hexagonal-to-do-list
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hexagonal-to-do-list?useSSL=false&serverTimeZone=UTC&allPublicKeyRetrival=true
    username: root
    password: root2904
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  pattern:
    dateformat: hh:mm
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE